language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle

services:
  - mongodb

before_script:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql

# script: gradle/wrapper wipe assemble --debug

after_success: gradle/wrapper clean check jacocoTestReport coveralls
