
language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb

before_script:
  #- sudo apt-get install -y graphviz
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql
  - tar -Jxvf ${TRAVIS_BUILD_DIR}/benchmark/assets/db.txz
  - mongorestore ${TRAVIS_BUILD_DIR}/benchmark/assets/dump/

script: gradle/wrapper check -d

after_success: gradle/wrapper javadoc site jacocoTestReport coveralls

# TODO after_failure cat logs to check problem
