language: java
jdk: oraclejdk8
after_success: ./gradlew clean check jacocoTestReport coveralls

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "JoIqS4Rww0dgiHSI9DQWOdPRKSMGDBTKwsXpg4HXhauZsgxPwcf3QQCjWVwTvJ8RrDcUjhYhb5sJOAbjdSc4xKFMNC7+Dip/0Focllmnj90gR+Ukk9uWNUhTspJiI3s5i+uPnpxvUQnIzoO5NxcTEywTziZGat8XRYzFbNaox0Q="

addons:
  coverity_scan:
    project:
      name: "jamming/sabina"
      description: "Build submitted via Travis CI"
    notification_email: juanjoaguililla@gmail.com
    build_command_prepend: "gradlew clean"
    build_command:   "gradlew check"
    branch_pattern: master
