
language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - .gradle
  - $HOME/.gradle

services:
  - mongodb

before_script:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql
  - tar -Jxvf ${TRAVIS_BUILD_DIR}/benchmark/assets/db.txz
  - mongorestore ${TRAVIS_BUILD_DIR}/benchmark/assets/dump/

script: gradle/wrapper wipe check -is

after_success: gradle/wrapper assemble javadoc site jacocoTestReport coveralls -is

# TODO after_failure cat logs to check problem
