
#
# TRAVIS BUILD
# Caching .gradle and not cleaning it (with 'wipe') causes the job to fail.
#

language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle

services:
  - mongodb

before_script:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql

script: gradle/wrapper wipe check

after_success: gradle/wrapper jacocoTestReport coveralls
