language: java
jdk: oraclejdk8

services:
  - mongodb

before_script:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql

after_success: gradle/wrapper --info clean check jacocoTestReport coveralls
