
language: java
jdk: oraclejdk8

sudo: false

cache:
  directories:
  - $HOME/.gradle

services:
  - mongodb

before_script:
  - mysql -u root < ${TRAVIS_BUILD_DIR}/benchmark/assets/db.sql

after_success: gradle/wrapper jacocoTestReport coveralls
